name: lint
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    strategy:
      matrix:
        runner: [[ubuntu-latest]]
        CMAKE_BUILD_TYPE: [Debug]
        BUILD_TESTING: [ON]
        BUILD_EXAMPLE: [ON]
        emcmake: ['']
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Run in devcontainer
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            # Change Ownership
            # sudo chown -R $USER .
            # Configure
            ${{ matrix.emcmake }} cmake -B build -S . -DCMAKE_BUILD_TYPE=${{ matrix.CMAKE_BUILD_TYPE }} -DBUILD_TESTING=${{ matrix.BUILD_TESTING }} -DBUILD_EXAMPLE=${{ matrix.BUILD_EXAMPLE }}
            # Lint
            cmake --build build --target check-format
