name: unittest
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unittest:
    strategy:
      matrix:
        runner: [[ubuntu-latest]]
        BUILD_TYPE: [Debug]
    runs-on: ${{ matrix.runner }}
    # Disable temporarily
    if: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Run in devcontainer
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            # Change Ownership
            sudo chown -R $USER .
            # Run unittest
            make unit
            ./build/unittest
            # Run coverage
            make coverage
    
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: build/coverage